CIE-726  Navigating to home page within 30 sec timeout of host driven scan mode greys out DL buttons
CredenceID/vds-webapp pull request #39
Opened 2023-10-03 04:15 UTC by vikrantcredence

This PR includes changes related to adding API call while navigating to Dashboard page from Information modal page and adding a new button to Information modal page which will redirect us to dashboard page

2023-10-03 06:05 UTC, naga-cid commented on vds-frontend/src/components/informationModal/InformationModal.jsx
> +                <span className="text-span">Please scan 2D barcode at the back of your DL</span>
remove if not necessary

2023-10-03 06:07 UTC, naga-cid commented on vds-frontend/src/containers/header/Header.jsx
> +              <Link to="/" onClick={this.props.indentityInfo ? stopInfo : null}>
change indentityInfo to indentityInfoInvoked

2023-10-03 06:16 UTC, naga-cid commented on vds-frontend/src/containers/header/Header.jsx
> +              <Link to="/" onClick={this.props.indentityInfo ? stopInfo : null}>
what happens if stopinfo API fails?

2023-10-03 06:18 UTC, naga-cid requested changes
Please check the comments

2023-10-03 12:19 UTC, vikrantcredence commented on vds-frontend/src/components/informationModal/InformationModal.jsx
> +                <span className="text-span">Please scan 2D barcode at the back of your DL</span>
Resolved with necessary changes

2023-10-03 12:19 UTC, vikrantcredence commented on vds-frontend/src/containers/header/Header.jsx
> +              <Link to="/" onClick={this.props.indentityInfo ? stopInfo : null}>
Resolved with necessary changes

2023-10-03 12:20 UTC, vikrantcredence commented on vds-frontend/src/containers/header/Header.jsx
> +              <Link to="/" onClick={this.props.indentityInfo ? stopInfo : null}>
Resolved with necessary changes

2023-10-05 12:55 UTC, naga-cid commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +    if (this.state.deviceStatus !== "") {
if (this.state.deviceStatus !== "") {

What is this check for?

2023-10-06 05:51 UTC, vikrantcredence commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +    if (this.state.deviceStatus !== "") {
We were facing an issue of reader info API getting called twice, so we had added this check to avoid two API calls. Because of this check we are calling info API call only when we get the device status.

2023-10-06 05:53 UTC, vikrantcredence commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +      if (localIdInfo === "true") {
necessary changes has been done. Please review once and let me know if there are suggestions.

2023-10-06 07:23 UTC, naga-cid commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +      } else if (localIdInfo === "false" && this.state.deviceStatus !== "") {
remove the false check

2023-10-06 07:24 UTC, naga-cid commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +      } else if (localIdInfo === "false" && this.state.deviceStatus !== "") {
add a comment for this.state.deviceStatus !== ""

2023-10-06 08:55 UTC, naga-cid commented on vds-frontend/src/App.scss
How about handling in identityAPI response?

2023-10-06 09:02 UTC, vikrantcredence commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +      } else if (localIdInfo === "false" && this.state.deviceStatus !== "") {
Necessary changes has been done

2023-10-06 09:04 UTC, vikrantcredence commented on vds-frontend/src/containers/dashboard/Dashboard.jsx
> +      } else if (localIdInfo === "false" && this.state.deviceStatus !== "") {
Necessary changes has been done

2023-10-06 09:05 UTC, vikrantcredence commented on vds-frontend/src/App.scss
Necessary changes has been done

2023-10-06 09:13 UTC, naga-cid approved these changes

2023-10-06 09:13 UTC, merged